export const ADD_PARTICIPANT = "ADD_PARTICIPANT";
export const REMOVE_PARTICIPANT = "REMOVE_PARTICIPANT";
export const CLEAR_PARTICIPANTS = "CLEAR_PARTICIPANT";

export const INCREMENT_IDCOUNTER = "INCREMENT_IDCOUNTER";
export const RESET_IDCOUNTER = "RESET_IDCOUNTER";
